### PR TITLE
fix(versions): update Activiti/activiti-dependencies versions

### PR DESCRIPTION
**Pull request by ghost**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.50`

### CODE REVIEW

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.api:activiti-api-dependencies 7.0.50 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.core.common:activiti-core-common-dependencies 7.0.16 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.core.common:activiti-core-common-dependencies 7.0.17 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti:activiti-core-dependencies 7.0.71 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti:activiti-core-dependencies 7.0.72 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti:activiti-core-dependencies 7.0.73 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.core.common:activiti-core-common-dependencies 7.0.18 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti:activiti-core-dependencies 7.0.74 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.core.common:activiti-core-common-dependencies 7.0.19 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti:activiti-core-dependencies 7.0.75 --merge false

**Review by salaboy — APPROVED** [review]
this is ready to be released

**Pull request merged**
