### PR TITLE
update org.activiti.api:activiti-api-dependencies to 7.0.3

### PR DESCRIPTION
**Pull request by ryandawsonuk**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.0`

### CODE REVIEW

**Comment by ryandawsonuk** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.api:activiti-api-dependencies 7.0.0

**Comment by ryandawsonuk** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.api:activiti-api-dependencies 7.0.1

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.api:activiti-api-dependencies 7.0.2

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.api:activiti-api-dependencies 7.0.3

**Pull request merged**
