### PR TITLE
fix(versions): update Activiti/activiti-dependencies versions

### PR DESCRIPTION
**Pull request by ghost**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.60`

### CODE REVIEW

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.build:activiti-parent 7.0.60 org.activiti.build:activiti-dependencies-parent 7.0.60 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.api:activiti-api-dependencies 7.0.87 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.core.common:activiti-core-common-dependencies 7.0.48 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.core.common:activiti-core-common-dependencies 7.0.49 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti:activiti-core-dependencies 7.0.128 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.api:activiti-api-dependencies 7.1.7 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.core.common:activiti-core-common-dependencies 7.1.5 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.build:activiti-parent 7.0.61 org.activiti.build:activiti-dependencies-parent 7.0.61 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.api:activiti-api-dependencies 7.0.88 --merge false

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.core.common:activiti-core-common-dependencies 7.0.50 --merge false

**Comment by ryandawsonuk** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.build:activiti-parent 7.0.TESTPR73

**Pull request closed without merging**
